const MenuApi = [
    {
        id:1,
        image:'images/maggi.jpg',
        name:'Maggi',
        category:'Brackfrist',
        price:'$30',
        description:'i love meggi and this is awesome it is very hard of tha country. bangladash maggi is awesome of food department.maggi is a verry hard fool maggi ogf our country in the world.bangladash maggi is awesome of food department.maggi is a verry hard fool maggi ogf our country in the world.',
    },
    {
        id:2,
        image:'images/bargar.jpg',
        name:'Bargar',
        category:'Lunch',
        price:'$20',
        description:'i love bargar and this is awesome it is very hard of tha country. bangladash bargar is awesome of food department.bargar is a verry hard fool maggi ogf our country in the world.bangladash maggi is awesome of food department.maggi is a verry hard fool maggi ogf our country in the world.',
    },
    {
        id:3,
        image:'images/kek.jpg',
        name:'Cack',
        category:'Lunch',
        price:'$50',
        description:'i love Cack and this is awesome it is very hard of tha country. bangladash Cack is awesome of food department.maggi is a verry hard fool Chicken ogf our country in the world.bangladash maggi is awesome of food department.maggi is a verry hard fool maggi ogf our country in the world.',
    },
    {
        id:4,
        image:'images/murgi.jpg',
        name:'Chicken',
        category:'Dinnar',
        price:'$80',
        description:'i love Chicken and this is awesome it is very hard of tha country. bangladash Chicken is awesome of food department.maggi is a verry hard fool Chicken ogf our country in the world.bangladash maggi is awesome of food department.maggi is a verry hard fool maggi ogf our country in the world.',
    },
    {
        id:5,
        image:'images/pirza.jpg',
        name:'Pirza',
        category:'Brackfrist',
        price:'$100',
        description:'i love Pirza and this is awesome it is very hard of tha country. bangladash Pirza is awesome of food department.Pirza is a verry hard fool Chicken ogf our country in the world.bangladash maggi is awesome of food department.maggi is a verry hard fool maggi ogf our country in the world.',
    },
    {
        id:6,
        image:'images/ran.jpg',
        name:'Run',
        category:'Lunch',
        price:'$45',
        description:'i love Run and this is awesome it is very hard of tha country. bangladash Run is awesome of food department.Run is a verry hard fool Chicken ogf our country in the world.bangladash maggi is awesome of food department.maggi is a verry hard fool maggi ogf our country in the world.',
    },
    {
        id:7,
        image:'images/ruti.jpg',
        name:'Ruti',
        category:'Dinnar',
        price:'$30',
        description:'i love Ruti and this is awesome it is very hard of tha country. bangladash Ruti is awesome of food department.Ruti is a verry hard fool Chicken ogf our country in the world.bangladash Ruti is awesome of food department.maggi is a verry hard fool Ruti ogf our country in the world.',
    },
]
export default MenuApi;